/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/invoice-details` | `/invoice-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/overlay` | `/overlay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/read-qr` | `/read-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}${'/(weather)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/types`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/invoice-details` | `/invoice-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/location` | `/location`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/overlay` | `/overlay`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/read-qr` | `/read-qr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}${'/(weather)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/types`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/invoice-details${`?${string}` | `#${string}` | ''}` | `/invoice-details${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/location${`?${string}` | `#${string}` | ''}` | `/location${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/maps${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/overlay${`?${string}` | `#${string}` | ''}` | `/overlay${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/read-qr${`?${string}` | `#${string}` | ''}` | `/read-qr${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}${'/(tabs)'}${'/(weather)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/invoice-details` | `/invoice-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/overlay` | `/overlay`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/read-qr` | `/read-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}${'/(tabs)'}${'/(weather)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/types`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
